# (OLD / DEPRECATED -- check .github/workflows)

language: python
python:
#- '3.7'
- '3.8'
#- 3.8-dev
#- nightly

install:
- pip install -r requirements-travis-1
- pip install -r requirements-travis-2

script:
#- pytest --cov
- make -C docs/ clean
- make -C docs/ html
- touch docs/build/html/.nojekyll

# Tests
#- git clone git@github.com:mieskolainen/travis-stash.git
- git clone https://github.com/mieskolainen/travis-stash.git
- source tests/runme_trg.sh
- source tests/runme_eid.sh
- source tests/runme_brk.sh

after_success:
#- coverage run --source=httpsuite -m pytest tests/
#- coveralls

deploy:
#  - provider: pypi
#    user: "__token__"
#    password: $PYPI_TOKEN
#    skip_existing: true
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true
