# Peakfit steering code
#
# Remember that yaml scientific notation requires 1.0 (dots)
# and (+) and (-) for the exponent (e.g. 1.0e+8)
#
#
# Tips: One can simplify the model by settings some parameters to
# their "symmetric" (e.g. 0) values and fixing those.
#
# m.mieskolainen@imperial.ac.uk, 2023

input_path:   './travis-stash/input/icefit/dqcd_2018_test/flat/muon/generalTracks/JPsi'
output_name:  'tune2'

years:    [2018] #[2016, 2017, 2018]

fitrange: [2.91, 3.29] # Nominal fit window (GeV)

systematics: ['Nominal'] # ['Nominal', 'nVertices_Up', 'nVertices_Down']

# List of systematic variations active
variations: ['DEFAULT'] #, 'MASS-WINDOW-DOWN', 'MASS-WINDOW-UP']

num_cpus: 0 # put 0 for automatic, set manually to 1 if problems (ray not used with 1)

fit_type: 'single' # 'single', 'dual', 'dual-unitary-I', 'dual-unitary-II'


fit:

  S:
    func:    'DSCB_pdf'
    args:
      norm:     True
    
    # Function weight (fit contribution) parameter
    theta_start:  100.0
    theta_limit:  [1.0e-4, 1.0e+5]
    theta_fixed:  False
    
    p_name:   ['M0', 'sigma', 'n_low', 'alpha_low', 'n_high', 'alpha_high']
    p_start:  [3.097, 0.03, 1.5, 1.1, 1.5, 1.1]
    p_limit:  [[3.085, 3.12], [0.015, 0.05], [1.001, 20.0], [0.001, 2.0], [1.001, 20.0], [0.001, 2.0]]
    p_fixed:  [False, False, False, False, False, False]
  
  B:
    func:    'exp_pdf'
    args:
      norm:     True
    
    # Function weight (fit contribution) parameter
    theta_start:  0.1
    theta_limit:  [1.0e-4, 1.0e+5]
    theta_fixed:  False

    p_name:   ['lambda']
    p_start:  [1.0e-4]
    p_limit:  [[1.0e-5, 4.0]]
    p_fixed:  [False]


  # Add here more fit components in linear superposition (only with 'single' mode), by giving a unique string label
  # ...


# Fit algorithm parameters
techno:
  rng_seed: 1234

  loss_type: 'chi2'                # 'chi2', 'huber', 'nll'
  use_limits: True                 # Use parameter bounds
  zerobin: 0.1                     # Minimum number of counts in a valid bin
  
  huber_delta: 1.0                 # 'huber' loss threshold parameter
  
  # Use enough calls / iterations (otherwise can get stuck in bad local minima)
  
  ncall_scipy_simplex: 0           # Number of scipy search calls
  ncall_mystic_diffev2:     1      # Number of Mystic solver calls
  ncall_mystic_fmin_powell: 1      # Number of Mystic solver calls

  ncall_minuit_scan:     0         # Number of brute force 1D-scan calls
  ncall_minuit_simplex:  0         # Number of Nelder-Mead simplex search calls
  ncall_minuit_gradient: 10000     # Number of Minuit gradient search calls
  
  minos: True       # If True, Minuit MINOS uncertainties (slower but best), otherwise HESSE

  min_ndof: 1       # Minimum number of d.o.f required
  max_chi2: 1200    # Maximum chi2/ndf for a succesful fit
  min_count: 5      # Minimum number of total entries (sum of bin content) in the histogram
  max_trials: 3     # Number of restarts

  set_to_nan: True  # Set parameters after the fit to NaN if not passing max_chi2 or min_count

  strategy: 1       # Default 1
  tol: 0.1          # Default 0.1, https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.tol

  cov_eps: 0.0      # Covariance matrix post-regularization (added to diagonal) (set to 0 for none, can bias!)
