# [0]
SIGNAL: &SIGNAL
  path: 'local-stash/input/icebrem/output_signal_1M'
  #files: 'output_0.root'
  files: 'output_[0-4].root'
  xs: 1.
  model_param: null
  force_xs: false
  isMC:     true
  maxevents_scale: 1.
