# Github actions CI (continous integration) setup.
#
# m.mieskolainen@imperial.ac.uk, 2023

name: icenet-install-test

on: [push, workflow_dispatch]

jobs:
  icenet-install-test:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'
      
      ## Install GPU tools
      # conda install -c nvidia cudatoolkit==11.7.0 cudnn==8.4.1.50
      # conda install -c conda-forge cudatoolkit-dev==11.7.0
      
      # Install conda packages
      
      # (needed e.g. for xgboost tree visualization)
      # conda install python-graphviz
      
      - name: Install pip-requirements
        run: |
          pip install -r requirements-github-actions-1.txt
          pip install -r requirements-github-actions-2.txt
      
      ## Docs building
      - name: Build docs
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
          make -C docs/ clean
          make -C docs/ html
          touch docs/build/html/.nojekyll

      ## Release to gh-pages
      - name: Release docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
      
      ## Unit tests
      - name: Unit tests
        run: |
          pytest icenet/tools/stx.py -rP
      
      ## Integration tests
      - name: Deep Learning system integration test (clone stash)
        run: |
          git clone https://github.com/mieskolainen/travis-stash.git
      
      - name: Deep Learning system integration test 1 (trg)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_trg.sh

      - name: Deep Learning system integration test 2 (hnl)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_hnl.sh

      - name: Deep Learning system integration test 3 (eid)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_eid.sh
      
      - name: Deep Learning system integration test 4 (eid_deep)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_eid_deep.sh
      
      - name: Deep Learning system integration test 5 (eid_visual)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_eid_visual.sh
        
        #  source setenv-github-actions.sh && python icefit/peakfit.py --analyze --group --inputfile ./configs/peakfit/tune2.yml

        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_brk.sh
        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_dqcd_vector_train.sh
        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_hgcal_cnd.sh
        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_hgcal_trk.sh

