# Github actions CI (continous integration) setup.
#
# m.mieskolainen@imperial.ac.uk, 2024

name: icenet-install-test

on: [push, workflow_dispatch]

jobs:
  icenet-install-test:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
      
      ## Install GPU tools
      # conda install -c conda-forge cudatoolkit==11.8.0 cudatoolkit-dev==11.8.0 cudnn=8.9.7.29
      
      # Install conda packages
      
      # (needed e.g. for xgboost tree visualization)
      # conda install python-graphviz
      
      - name: Install pip-requirements
        run: |
          pip install -r requirements-github-actions-1.txt
          pip install -r requirements-github-actions-2.txt
      
      ## Docs building
      - name: Build docs
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
          make -C docs/ clean
          make -C docs/ html
          touch docs/build/html/.nojekyll

      ## Release to gh-pages
      - name: Release docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
      
      ## Unit tests
      - name: Unit tests
        run: |
          pytest icenet/tools/stx.py -rP
          pytest icenet/tools/supertune.py -rP
          pytest icefit/transport.py -rP
          pytest icefit/cortools.py -rP
      
      ## Integration tests
      - name: Deep Learning system integration test (clone stash)
        run: |
          git clone https://github.com/mieskolainen/travis-stash.git
      
      #
      - name: Peakfit (single)
        run: |
          source setenv-github-actions.sh && python icefit/peakfit.py --analyze --group --test_mode --fit_type single --output_name single
      
      #
      - name: Peakfit (dual)
        run: |
          source setenv-github-actions.sh && python icefit/peakfit.py --analyze --group --test_mode --fit_type dual --output_name dual
      
      #
      - name: Peakfit (dual-unitary-I)
        run: |
          source setenv-github-actions.sh && python icefit/peakfit.py --analyze --group --test_mode --fit_type dual-unitary-I --output_name dual-unitary-I
      
      #
      - name: Peakfit (dual-unitary-II)
        run: |
          source setenv-github-actions.sh && python icefit/peakfit.py --analyze --group --test_mode --fit_type dual-unitary-II --output_name dual-unitary-II
      
      #
      - name: Deep Learning system integration test (brem 1)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_brem.sh
      
      #
      - name: Deep Learning system integration test (brem 2)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_brem_reweight.sh
      
      #
      - name: Deep Learning system integration test (zee 1)
        run: |
          source setenv-github-actions.sh && maxevents=1000; source tests/runme_zee.sh       && echo "yes" | source superclean.sh
      
      #
      - name: Deep Learning system integration test (zee 2)
        run: |
          source setenv-github-actions.sh && maxevents=1000; source tests/runme_zee_mixed.sh && echo "yes" | source superclean.sh
      
      #
      - name: Deep Learning system integration test (hnl 1)
        run: |
          source setenv-github-actions.sh && maxevents=1000; source tests/runme_hnl.sh
      
      #
      - name: Deep Learning system integration test (trg 1)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_trg.sh

      #
      - name: Deep Learning system integration test (eid 1)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_eid.sh
      
      #
      - name: Deep Learning system integration test (eid_deep 1)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_eid_deep.sh
      
      #
      - name: Deep Learning system integration test (eid_visual 1)
        run: |
          source setenv-github-actions.sh && maxevents=10000; source tests/runme_eid_visual.sh

        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_brk.sh
        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_dqcd_vector_train.sh
        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_hgcal_cnd.sh
        ## source setenv-github-actions.sh && maxevents=10000; source tests/runme_hgcal_trk.sh

